### ISSUE TITLE
Handle exception when no results were found in es

### ISSUE THREAD

**Issue by yaelmi3** [yaelmi3/utils#15]
Traceback (most recent call last):
  File "utils.py", line 291, in <module>
    baker.run()
  File "/Users/ymintz/infi/infi_env/lib/python3.6/site-packages/baker.py", line 888, in run
    value = self.apply(*self.parse(argv), instance=instance)
  File "/Users/ymintz/infi/infi_env/lib/python3.6/site-packages/baker.py", line 866, in apply
    return cmd.fn(*newargs, **newkwargs)
  File "utils.py", line 285, in get_failed_tests_by_name
    html_text = create_tests_table(tests)
  File "utils.py", line 105, in create_tests_table
    html_text += f"<tr>{''.join([cell.format(value) for value in tests[0].__dict__.keys()])}</tr>"
IndexError: list index out of range

**Comment by yaelmi3** [comment]
Fixed as part of https://github.com/yaelmi3/utils/tree/move_to_elastic_search
